main: pt.ganda.thecrimscraft.Main
name: TheCrimsCraft
version: 1.0
author: whaiiz
description: hello

commands:
  Help:
    usage: /<command>
  StoreTheft:
    usage: /<command>
  StoreTheftSetup:
    usage: /<command>
